# Generated by Django 5.1.2 on 2024-10-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_siteconfig_color_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_we_love',
            field=models.BooleanField(default=False),
        ),
    ]
