# Generated by Django 5.1.2 on 2024-10-25 18:00

import django.core.validators
import django.db.models.deletion
import snowflake.snowflake
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_product_we_love'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InnavatorUser',
            fields=[
                ('snowflake_id', models.BigIntegerField(default=snowflake.snowflake.SnowflakeGenerator.__next__, primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('full_name', models.CharField(blank=True, max_length=300, verbose_name='Full Name')),
                ('preferred_name', models.CharField(blank=True, max_length=150, verbose_name='Preferred Name')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='Major')),
                ('website_url', models.URLField(blank=True, max_length=300, validators=[django.core.validators.URLValidator()], verbose_name='Website URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.innavatoruser')),
                ('gradient1', models.CharField(default='#000000 #000000', max_length=15, validators=[django.core.validators.RegexValidator(regex='^#[0-9a-fA-F]{6} #[0-9a-fA-F]{6}$')], verbose_name='First Gradient')),
                ('gradient2', models.CharField(default='#000000 #000000', max_length=15, validators=[django.core.validators.RegexValidator(regex='^#[0-9a-fA-F]{6} #[0-9a-fA-F]{6}$')], verbose_name='Second Gradient')),
                ('gradient3', models.CharField(default='#000000 #000000', max_length=15, validators=[django.core.validators.RegexValidator(regex='^#[0-9a-fA-F]{6} #[0-9a-fA-F]{6}$')], verbose_name='Third Gradient')),
                ('gradient4', models.CharField(default='#000000 #000000', max_length=15, validators=[django.core.validators.RegexValidator(regex='^#[0-9a-fA-F]{6} #[0-9a-fA-F]{6}$')], verbose_name='Fourth Gradient')),
                ('gradient5', models.CharField(default='#000000 #000000', max_length=15, validators=[django.core.validators.RegexValidator(regex='^#[0-9a-fA-F]{6} #[0-9a-fA-F]{6}$')], verbose_name='Fifth Gradient')),
                ('gradient6', models.CharField(default='#000000 #000000', max_length=15, validators=[django.core.validators.RegexValidator(regex='^#[0-9a-fA-F]{6} #[0-9a-fA-F]{6}$')], verbose_name='Sixth Gradient')),
            ],
        ),
    ]
