# Generated by Django 5.1.2 on 2024-10-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_innavatoruser_snowflake_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innavatoruser',
            name='snowflake_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID'),
        ),
    ]
