# Generated by Django 5.1.2 on 2024-10-28 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_innavatoruser_profile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('name', models.CharField(max_length=100, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('is_privileged', models.BooleanField(default=False, verbose_name='Is Privileged')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatoruser')),
            ],
        ),
        migrations.CreateModel(
            name='InnavatorGroup',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_club', models.BooleanField(default=False, verbose_name='Is Club')),
                ('members', models.ManyToManyField(related_name='%(app_label)s_%(class)s_members', through='store.GroupMembership', to='store.innavatoruser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owner', to='store.innavatoruser')),
            ],
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatorgroup'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('start_time', models.DateTimeField(verbose_name='Start Timestamp')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatorgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatorgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_mentee', to='store.innavatoruser')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_mentor', to='store.innavatoruser')),
            ],
        ),
        migrations.AddField(
            model_name='innavatoruser',
            name='mentors',
            field=models.ManyToManyField(through='store.Mentorship', to='store.innavatoruser'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('contents', models.CharField(max_length=2000, verbose_name='Contents')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is Edited')),
                ('last_revision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Revision')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.channel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatoruser')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatorgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatorgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRoleNeed',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.role')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatoruser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.role')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='looking_for_roles',
            field=models.ManyToManyField(through='store.ProjectRoleNeed', to='store.role'),
        ),
        migrations.CreateModel(
            name='CommissionRequest',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('message_contents', models.CharField(blank=True, max_length=2000, verbose_name='Message Contents')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatoruser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.role')),
            ],
        ),
    ]
