# Generated by Django 5.1.2 on 2024-10-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_role_groupmembership_innavatorgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionrequest',
            name='message_contents',
        ),
        migrations.AddField(
            model_name='commissionrequest',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='commissionrequest',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
