# Generated by Django 5.1.2 on 2024-10-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_testimonial_reviewer_location_squashed_0015_remove_commissionrequest_message_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
