# Generated by Django 5.1.2 on 2024-10-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_commissionrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_revision',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last Revision'),
        ),
    ]
