# Generated by Django 5.1.2 on 2024-10-30 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_message_last_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palette',
            name='gradient1',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='gradient2',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='gradient3',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='gradient4',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='gradient5',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='gradient6',
        ),
        migrations.AddField(
            model_name='palette',
            name='main_background_gradient_triplet',
            field=models.CharField(default='#FF9156 #92259A #BA2045', max_length=23, validators=[django.core.validators.RegexValidator(regex='^#[0-9a-fA-F]{6} #[0-9a-fA-F]{6} #[0-9a-fA-F]{6}$')], verbose_name='Main Background Gradient'),
        ),
        migrations.AddField(
            model_name='palette',
            name='ui_group_background_gradient_triplet',
            field=models.CharField(default='#FDF6C4 #D98CE3 #D26E8C', max_length=23, validators=[django.core.validators.RegexValidator(regex='^#[0-9a-fA-F]{6} #[0-9a-fA-F]{6} #[0-9a-fA-F]{6}$')], verbose_name='UI Group Background Gradient'),
        ),
    ]
