# Generated by Django 5.1.2 on 2024-11-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_innavatoruser_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innavatoruser',
            old_name='mentors',
            new_name='mentees',
        ),
    ]
