# Generated by Django 5.1.2 on 2024-11-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_mentorship_mentee_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='group_accepted',
            field=models.BooleanField(default=False, verbose_name='Group Accepted'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='request_message',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Request Message'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user_accepted',
            field=models.BooleanField(default=False, verbose_name='User Accepted'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='request_message',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Request Message'),
        ),
    ]
