# Generated by Django 5.1.2 on 2024-11-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_groupmembership_group_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='read_restricted',
            field=models.BooleanField(default=False, verbose_name='Read Restricted'),
        ),
        migrations.AddField(
            model_name='channel',
            name='write_restricted',
            field=models.BooleanField(default=False, verbose_name='Write Restricted'),
        ),
        migrations.CreateModel(
            name='LastRead',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('last_read', models.BigIntegerField(default=0, verbose_name='Last Read Message')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatoruser')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='last_read_list',
            field=models.ManyToManyField(through='store.LastRead', to='store.innavatoruser'),
        ),
    ]
