# Generated by Django 5.1.2 on 2024-11-09 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_channel_read_restricted_channel_write_restricted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioentry',
            options={'verbose_name_plural': 'Portfolio entries'},
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatoruser'),
        ),
    ]
