# Generated by Django 5.1.2 on 2024-11-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='project_accepted',
            field=models.BooleanField(default=False, verbose_name='Group Accepted'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='request_message',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Request Message'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='user_accepted',
            field=models.BooleanField(default=False, verbose_name='User Accepted'),
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
