# Generated by Django 5.1.2 on 2024-11-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_projectrole_project_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='WillingnessToTutor',
            fields=[
                ('snowflake_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Snowflake ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.innavatoruser')),
            ],
        ),
        migrations.AddField(
            model_name='innavatoruser',
            name='willing_to_tutor',
            field=models.ManyToManyField(through='store.WillingnessToTutor', to='store.subject'),
        ),
    ]
