# Generated by Django 5.1.2 on 2024-11-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_subject_willingnesstotutor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='willingnesstotutor',
            options={'verbose_name_plural': 'Willingnesses to mentor'},
        ),
    ]
