# Generated by Django 5.1.2 on 2024-12-02 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_willingnesstotutor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='picture_url',
            field=models.URLField(blank=True, max_length=300, validators=[django.core.validators.URLValidator()], verbose_name='Picture URL'),
        ),
    ]
