# Generated by Django 5.1.2 on 2024-12-03 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_portfolioentry_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subject'),
        ),
    ]
