# Generated by Django 5.1.2 on 2024-12-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_project_is_interactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='SiteConfig',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
